export type ServiceId =
  | 'trade-agency-recording'
  | 'trade-mark-recording'
  | 'rafed-information'
  | 'trade-ip-complaint'
  | 'customs-opinion'
  | 'appeal-customs-decision'
  | 'track-status'
  | 'pay-bills'
  | 'goods-classification'
  | 'request-certificates'
  | 'business-registration'
  | 'duty-account'
  | 'aeo-program'
  | 'warehouse-license'
  | 'accreditation'
  | 'cargo-information'
  | 'voluntary-disclosure'
  | 'customs-declaration'
  | 'cargo-transfer'
  | 'customs-inspection'
  | 'refund-claim'
  | 'customs-transactions'
  | 'temporary-admission'
  | 'representative-card'
  | 'view-announcements'
  | 'view-policies'
  | 'view-notices';

export interface ServiceDef {
  id: ServiceId;
  title: string;
  subtitle: string;
  description: string;
  locked: boolean;
  hasInfo: boolean;
  formType: 'full' | 'simple' | 'track' | 'pay-bills' | 'none';
  serviceName: string;
  serviceDescription: string;
  requirements: string;
  charges: string;
  fee: string;
  feeNote: string;
  steps: { label: string }[];
  deliveryChannels: string[];
  completionTime: string;
  relationshipType: string[];
  targetCategory: string;
  serviceType: string;
  serviceHierarchy: string;
  icon: string;
  iconFile?: string;
}

export const SERVICES: ServiceDef[] = [
  {
    id: 'business-registration',
    title: 'Request Business Registration - Dubai Customs',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Register the agency rights with Dubai Customs to allow them officially and legally transact with Dubai Customs.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Request Business Registration',
    serviceDescription: 'This service allows customers to register their business with Dubai Customs to officially transact with Customs.',
    requirements: 'A valid copy of the business registration certificate issued by the Ministry of Economy',
    charges: '200.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Pay service fees' },
      { label: 'Receive the certificate.' },
    ],
    deliveryChannels: ['Port Rashid Center - IPR Department', 'Website', 'Mobile Web'],
    completionTime: '2 Working Hours',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '🏢',
    iconFile: '/icons/Request Business Registration - Dubai Customs.svg',
  },
  {
    id: 'trade-agency-recording',
    title: 'Request Trade Agency Recording',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'This service allows customers to record their agency rights with Dubai Customs, which is pre-registered in the Ministry of Economy. Such recording allows the customers to file complaints with valid information on the imported of goods of registered agents by any unauthorized importers.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Record Trade Agency',
    serviceDescription: 'This service allows clients to record their agency rights with Dubai Customs which is pre-recorded in the Ministry of Economy. Such registration allows the clients to file complaints with specific information on violating imports by any unauthorised importers.',
    requirements: 'A valid copy of the trade agency registration certificate issued by the Ministry of Economy',
    charges: '200.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Pay service fees' },
      { label: 'Receive the certificate.' },
    ],
    deliveryChannels: ['Port Rashid Center - IPR Department', 'Website', 'Mobile Web'],
    completionTime: '2 Working Hours',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '📋',
    iconFile: '/icons/Request Trade Agency Recording.svg',
  },
  {
    id: 'trade-mark-recording',
    title: 'Request Trade Mark Recording',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'This service allows the Trademark Owners to record their registered Trade mark and Copy Right which are pre-recorded in the Ministry of Economy for the Customs protection. Such recording allows the customers to file complaints with specific information on violating Imports by any unauthorized importers.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Record Trade Mark',
    serviceDescription: 'This service allows clients to record Trade mark and Copy Right which are pre-recorded in the Ministry of Economy and valid for the purposes of customs protection. Such registration allows the clients to file complaints with specific information on violating imports by any unauthorised importers.',
    requirements: '1. A valid copy of the trademark registration certificate issued by the Ministry of Economy\n2. A duly authenticated and translated copy of the Power of Attorney',
    charges: '200.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Pay service fees' },
      { label: 'Receive the certificate.' },
    ],
    deliveryChannels: ['Port Rashid Center - IPR Department', 'Website', 'Mobile Web'],
    completionTime: '2 Working Days',
    relationshipType: ['From Government to Business', 'From Government to Individuals'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '™️',
    iconFile: '/icons/Request Trade Mark Recording.svg',
  },
  {
    id: 'trade-ip-complaint',
    title: 'Submit Trade Intellectual Property Complaint',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'This service allows the Trademark Owners to record their registered Trade mark and Copy Right which are pre-registered in the Ministry of Economy for the Customs protection. Such recording allows the customers to file complaints with valid information on Intellectual Property Infringement or Trade.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Submit Trade Intellectual Property Complaint',
    serviceDescription: 'This service allows clients to file a complaint on Intellectual Property infringement or Trade Agency',
    requirements: 'A valid copy of the trademark or intellectual property registration certificate',
    charges: '200.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Pay service fees' },
      { label: 'Receive the certificate.' },
    ],
    deliveryChannels: ['Port Rashid Center - IPR Department', 'Website', 'Mobile Web'],
    completionTime: '2 Working Hours',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '⚖️',
    iconFile: '/icons/Submit Trade Intellectual Property Complaint.svg',
  },
  {
    id: 'rafed-information',
    title: 'Submit RAFED Information',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'This service is designed to report any violations of customs so that these communications were divided into three main areas: Reporting Trade Mark and CopyRights, Reporting Trade Agency Violations, and To provide information relating to safety and security.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Submit RAFED Information',
    serviceDescription: 'This service is specifically designed for parties wishing to share intelligence information with Dubai Customs for public safety and to help expose corruption, suspicious activities or malpractices.\nThis service is meant to encourage community members to help Dubai Customs in maintaining the security and stability of society.\nThe Identity of the submitter is kept secret according with the regulations of Dubai Customs.',
    requirements: 'Valid identification document',
    charges: '0.0',
    fee: 'Free',
    feeNote: 'This service is provided free of charge',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Review by authorities' },
      { label: 'Receive confirmation.' },
    ],
    deliveryChannels: ['Website', 'Mobile Web'],
    completionTime: '2 Working Hours',
    relationshipType: ['From Government to Business', 'From Government to Individuals'],
    targetCategory: 'Companies',
    serviceType: 'Informational',
    serviceHierarchy: 'Sub Service',
    icon: '🛡️',
    iconFile: '/icons/Submit RAFED Information.svg',
  },
  {
    id: 'customs-opinion',
    title: 'Request Customs Opinion',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Request Customs Opinion',
    serviceDescription: 'This service provides recommendations and technical opinions to customers through a competent work teams in several areas and as per customer needs.\nThe focus of these recommendations and technical opinions covers the below areas:\n• Customs Valuation\n• Customs Tariff\n• Origin and Economic Agreements\n• Suspended Customs Duties\n• Prohibited and Restricted Goods\n• Customs Notices',
    requirements: 'Detailed description of goods and supporting documents',
    charges: '0',
    fee: 'AED 0.00',
    feeNote: '',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Pay service fees' },
      { label: 'Receive the opinion.' },
    ],
    deliveryChannels: ['Port Rashid Center - IPR Department', 'Website', 'Mobile Web'],
    completionTime: '3 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '💬',
    iconFile: '/icons/Request Customs Opinion.svg',
  },
  {
    id: 'appeal-customs-decision',
    title: 'Appeal Customs Decision',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Appeal on Customs Decision',
    serviceDescription: 'This service allows customers the opportunity to appeal any decision issued by Dubai Customs that does not fulfill their needs.\nThis service is the first step to be followed in order to find a way to challenge the decision provided by customs.\nThe customer can submit a request to appeal to resolve any issue in the following areas:\n• Appeal Decisions on Customs Tariff\n• Appeal Decisions on Prohibition and Restriction\n• Appeal Decisions on Origin and Economic Agreements\n• Appeal Decisions on Legal Cases\n• Appeal Decisions on Suspended Duties\n• Appeal Decisions on Customs Valuation\n• Appeal Decisions on Claim/ Forfeiture Demand Notice/ Invoice',
    requirements: 'Attach the evidences and proofs',
    charges: '200.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit the application through all available channels' },
      { label: 'Pay service fees' },
      { label: 'Receive decision.' },
    ],
    deliveryChannels: ['Port Rashid Center - IPR Department', 'Website', 'Mobile Web'],
    completionTime: '5 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '📝',
    iconFile: '/icons/Appeal Customs Decision.svg',
  },
  {
    id: 'goods-classification',
    title: 'Request Goods Classification',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'This service provides the ability to request for a classification of a commodity according to the unified customs tariff of the GCC countries.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Request Goods Classification',
    serviceDescription: 'This service provides the ability to request for a classification of a commodity according to the unified customs tariff of the GCC countries.',
    requirements: '1. Attachment based on commodity or case type, such as: Chemicals (Data Sheet) , Other Materials (Catalogs, Brochure, Photos, sample if required)',
    charges: '25.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit goods details and documentation' },
      { label: 'Pay service fees' },
      { label: 'Receive classification certificate.' },
    ],
    deliveryChannels: ['Port Rashid Center', 'Website', 'Mobile Web'],
    completionTime: '3 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '📦',
    iconFile: '/icons/Request Goods Classification.svg',
  },
  {
    id: 'pay-bills',
    title: 'Pay Bills or Fines',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelet',
    locked: false,
    hasInfo: true,
    formType: 'pay-bills',
    serviceName: 'Pay Bills or Fines',
    serviceDescription: 'This service allows customers to pay outstanding bills and fines related to customs activities.',
    requirements: 'Valid bill or fine reference number',
    charges: 'Varies',
    fee: 'Varies',
    feeNote: 'Amount based on the outstanding bill or fine',
    steps: [
      { label: 'Retrieve bill or fine details' },
      { label: 'Review and confirm amount' },
      { label: 'Complete payment.' },
    ],
    deliveryChannels: ['Website', 'Mobile Web', 'Dubai Now'],
    completionTime: 'Immediate',
    relationshipType: ['From Government to Business', 'From Government to Individuals'],
    targetCategory: 'Companies & Individuals',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '💳',
    iconFile: '/icons/Pay Bills or Fines.svg',
  },
  {
    id: 'request-certificates',
    title: 'Request Certificates',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: false,
    hasInfo: true,
    formType: 'full',
    serviceName: 'Request Certificates',
    serviceDescription: 'This service allows customers to request various certificates issued by Dubai Customs for trade purposes.',
    requirements: 'Valid trade registration and supporting documents',
    charges: '200.0',
    fee: 'AED 200.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit the application' },
      { label: 'Pay service fees' },
      { label: 'Receive certificate.' },
    ],
    deliveryChannels: ['Port Rashid Center', 'Website', 'Mobile Web'],
    completionTime: '2 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '🏆',
    iconFile: '/icons/Request Certificates.svg',
  },
  {
    id: 'track-status',
    title: 'Track Service Status',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelet',
    locked: false,
    hasInfo: true,
    formType: 'track',
    serviceName: 'Track Service Status',
    serviceDescription: 'Track the status of your submitted service requests in real time.',
    requirements: 'Service request reference number',
    charges: '0.0',
    fee: 'Free',
    feeNote: 'This service is provided free of charge',
    steps: [
      { label: 'Enter your service type and request number' },
      { label: 'Verify identity with captcha' },
      { label: 'View real-time status.' },
    ],
    deliveryChannels: ['Website', 'Mobile Web'],
    completionTime: 'Immediate',
    relationshipType: ['From Government to Business', 'From Government to Individuals'],
    targetCategory: 'Companies & Individuals',
    serviceType: 'Informational',
    serviceHierarchy: 'Sub Service',
    icon: '🔍',
    iconFile: '/icons/Track Service Status.svg',
  },
  {
    id: 'duty-account',
    title: 'Request Duty Account',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: true,
    hasInfo: true,
    formType: 'none',
    serviceName: 'Request Duty Account',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '🔒',
  },
  {
    id: 'aeo-program',
    title: 'Join Authorized Economic Operator Program',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Authorized economic operators to join the AEO program',
    locked: false,
    hasInfo: true,
    formType: 'simple',
    serviceName: 'Join Authorized Economic Operator Program',
    serviceDescription: 'Join the AEO program for streamlined customs procedures and facilitated trade.',
    requirements: 'Valid trade license and compliance records',
    charges: '500.0',
    fee: 'AED 500.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added on top of any service costs AED 50 and above',
    steps: [
      { label: 'Submit application and documentation' },
      { label: 'Undergo assessment' },
      { label: 'Receive AEO certificate.' },
    ],
    deliveryChannels: ['Website', 'Mobile Web'],
    completionTime: '30 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '🌐',
  },
  {
    id: 'warehouse-license',
    title: 'Request Customs Warehouse License',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Obtain a Customs Warehouse License that is used to store goods under the...',
    locked: false,
    hasInfo: true,
    formType: 'simple',
    serviceName: 'Request Customs Warehouse License',
    serviceDescription: 'Obtain a Customs Warehouse License to store goods under customs supervision.',
    requirements: 'Valid trade license and warehouse specifications',
    charges: '1000.0',
    fee: 'AED 1000.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added',
    steps: [
      { label: 'Submit application' },
      { label: 'Site inspection' },
      { label: 'Receive license.' },
    ],
    deliveryChannels: ['Website', 'Mobile Web'],
    completionTime: '10 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '🏭',
  },
  {
    id: 'accreditation',
    title: 'Join Accreditation Program',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Submit a request for enrollment in Dubai Customs Accreditation Program.',
    locked: false,
    hasInfo: true,
    formType: 'simple',
    serviceName: 'Join Accreditation Program',
    serviceDescription: 'Submit a request for enrollment in Dubai Customs Accreditation Program.',
    requirements: 'Valid trade license and compliance history',
    charges: '300.0',
    fee: 'AED 300.00',
    feeNote: 'AED 20 Knowledge and Innovation fees will be added',
    steps: [
      { label: 'Submit application' },
      { label: 'Review and assessment' },
      { label: 'Receive accreditation.' },
    ],
    deliveryChannels: ['Website', 'Mobile Web'],
    completionTime: '15 Working Days',
    relationshipType: ['From Government to Business'],
    targetCategory: 'Companies',
    serviceType: 'Transactional',
    serviceHierarchy: 'Sub Service',
    icon: '🎓',
  },
  {
    id: 'cargo-information',
    title: 'Submit Cargo Information',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Carriers/Agents to submit Cargo Information Documents, Manifests, etc.',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '🚢',
  },
  {
    id: 'voluntary-disclosure',
    title: 'Submit Voluntary Disclosure',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Voluntarily disclose errors and violations committed in customs declaration.',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '📣',
  },
  {
    id: 'customs-declaration',
    title: 'Submit Customs Declaration',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Declare and obtain clearance for the movement of goods in and out of the...',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '📄',
  },
  {
    id: 'cargo-transfer',
    title: 'Request Cargo Transfer',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Request to move consolidated cargo to their customs-certified premises for d...',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '🚛',
  },
  {
    id: 'customs-inspection',
    title: 'Book Customs Inspection',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelet',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '🔎',
  },
  {
    id: 'refund-claim',
    title: 'Submit Refund Claim',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '💰',
  },
  {
    id: 'customs-transactions',
    title: 'Request Customs Transactions Report',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Declare and obtain clearance for the movement, aliquet scelerisque dignissim tellus...',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '📊',
  },
  {
    id: 'temporary-admission',
    title: 'Request Temporary Admission Extension',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Request to move consolidated cargo to their customers, aliquet sceleri...',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '⏱️',
  },
  {
    id: 'representative-card',
    title: 'Request Representative Card',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Request for a representative card to carry out all authorized company transactions...',
    locked: true,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '🪪',
  },
  {
    id: 'view-announcements',
    title: 'View Announcements',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: false,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '📢',
  },
  {
    id: 'view-policies',
    title: 'View Customs Policies',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: false,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '📋',
  },
  {
    id: 'view-notices',
    title: 'View Customs Notices',
    subtitle: 'Cursus purus, diam, aliquet sceleri',
    description: 'Cursus purus, diam, aliquet scelerisque dignissim tellus aenean viverra.',
    locked: false,
    hasInfo: false,
    formType: 'none',
    serviceName: '',
    serviceDescription: '',
    requirements: '',
    charges: '',
    fee: '',
    feeNote: '',
    steps: [],
    deliveryChannels: [],
    completionTime: '',
    relationshipType: [],
    targetCategory: '',
    serviceType: '',
    serviceHierarchy: '',
    icon: '📰',
  },
];

export function getService(id: string): ServiceDef | undefined {
  return SERVICES.find((s) => s.id === id);
}
